default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-merge-conflict
-   repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort (python)
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        args: [
            --max-line-length=80,
            --literal-inline-quotes=double,
            --literal-multiline-quotes=double,
            --inline-quotes=double
        ]
        additional_dependencies: [
            flake8-requirements==1.7.5,
            flake8-warnings==0.3.0,
            flake8-variables-names==0.0.5,
            flake8-return==1.2.0,
            flake8-comprehensions==3.10.1,
            flake8-quotes==3.3.1
        ]